-- MySQL Script generated by MySQL Workbench
-- Mon Dec 25 20:57:39 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

drop database solvd_task;

-- -----------------------------------------------------
-- Schema solvd_task
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema solvd_task
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `solvd_task` DEFAULT CHARACTER SET utf8 ;
USE `solvd_task` ;

-- -----------------------------------------------------
-- Table `solvd_task`.`supermarkets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solvd_task`.`supermarkets` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `supermarket_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `solvd_task`.`departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solvd_task`.`departments` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `task` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `supermarket_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_departments_supermarkets1_idx` (`supermarket_id` ASC) VISIBLE,
  CONSTRAINT `fk_department_supermarket`
    FOREIGN KEY (`supermarket_id`)
    REFERENCES `solvd_task`.`supermarkets` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `solvd_task`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solvd_task`.`employees` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `age` INT NOT NULL,
  `supermarket_id` BIGINT UNSIGNED NOT NULL,
  `department_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `supermarket_id`),
  UNIQUE INDEX `employee_id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_employees_supermarkets1_idx` (`supermarket_id` ASC) VISIBLE,
  INDEX `fk_employees_departments1_idx` (`department_id` ASC) VISIBLE,
  CONSTRAINT `fk_employee_supermarket`
    FOREIGN KEY (`supermarket_id`)
    REFERENCES `solvd_task`.`supermarkets` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_department`
    FOREIGN KEY (`department_id`)
    REFERENCES `solvd_task`.`departments` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `solvd_task`.`providers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solvd_task`.`providers` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `provider_name` VARCHAR(45) NOT NULL,
  `provider_branch` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `provider_name_UNIQUE` (`provider_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `solvd_task`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solvd_task`.`products` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `supermarket_id` BIGINT UNSIGNED NOT NULL,
  `provider_id` BIGINT UNSIGNED NOT NULL,
  `product_name` VARCHAR(255) NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `price` DECIMAL NOT NULL,
  PRIMARY KEY (`id`, `supermarket_id`),
  UNIQUE INDEX `product_id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_products_supermarkets1_idx` (`supermarket_id` ASC) VISIBLE,
  INDEX `fk_products_providers1_idx` (`provider_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_supermarket`
    FOREIGN KEY (`supermarket_id`)
    REFERENCES `solvd_task`.`supermarkets` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_providers`
    FOREIGN KEY (`provider_id`)
    REFERENCES `solvd_task`.`providers` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `solvd_task`.`supervisors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solvd_task`.`supervisors` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `department_id` BIGINT UNSIGNED NOT NULL,
  `employee_id` BIGINT UNSIGNED NOT NULL,
  `employee_supermarket_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_supervisors_departments1_idx` (`department_id` ASC) VISIBLE,
  INDEX `fk_supervisors_employees1_idx` (`employee_id` ASC, `employee_supermarket_id` ASC) VISIBLE,
  CONSTRAINT `fk_supervisor_department`
    FOREIGN KEY (`department_id`)
    REFERENCES `solvd_task`.`departments` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_supervisor_employee`
    FOREIGN KEY (`employee_id` , `employee_supermarket_id`)
    REFERENCES `solvd_task`.`employees` (`id` , `supermarket_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `solvd_task`.`supermarket_providers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solvd_task`.`supermarket_providers` (
  `supermarket_id` BIGINT UNSIGNED NOT NULL,
  `provider_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`supermarket_id`, `provider_id`),
  INDEX `fk_supermarkets_has_providers_providers1_idx` (`provider_id` ASC) VISIBLE,
  INDEX `fk_supermarkets_has_providers_supermarkets1_idx` (`supermarket_id` ASC) VISIBLE,
  CONSTRAINT `fk_supermarket_providers`
    FOREIGN KEY (`supermarket_id`)
    REFERENCES `solvd_task`.`supermarkets` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_supermarket_has_providers`
    FOREIGN KEY (`provider_id`)
    REFERENCES `solvd_task`.`providers` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `solvd_task`.`meats_sector`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solvd_task`.`meats_sector` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `expiration_date` VARCHAR(45) NOT NULL,
  `product_id` BIGINT UNSIGNED NOT NULL,
  `product_supermarket_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_meats_sector_products1_idx` (`product_id` ASC, `product_supermarket_id` ASC) VISIBLE,
  CONSTRAINT `fk_meats_sector_products`
    FOREIGN KEY (`product_id` , `product_supermarket_id`)
    REFERENCES `solvd_task`.`products` (`id` , `supermarket_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `solvd_task`.`cleanings_sector`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solvd_task`.`cleanings_sector` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `product_id` BIGINT UNSIGNED NOT NULL,
  `product_supermarket_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_cleanings_sector_products1_idx` (`product_id` ASC, `product_supermarket_id` ASC) VISIBLE,
  CONSTRAINT `fk_cleanings_sector_products`
    FOREIGN KEY (`product_id` , `product_supermarket_id`)
    REFERENCES `solvd_task`.`products` (`id` , `supermarket_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `solvd_task`.`fruits_sector`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solvd_task`.`fruits_sector` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `product_id` BIGINT UNSIGNED NOT NULL,
  `product_supermarket_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_fruits_sector_products1_idx` (`product_id` ASC, `product_supermarket_id` ASC) VISIBLE,
  CONSTRAINT `fk_fruits_sector_products`
    FOREIGN KEY (`product_id` , `product_supermarket_id`)
    REFERENCES `solvd_task`.`products` (`id` , `supermarket_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `solvd_task`.`cereal_sector`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solvd_task`.`cereal_sector` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `flavour` VARCHAR(45) NOT NULL,
  `product_id` BIGINT UNSIGNED NOT NULL,
  `products_supermarket_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_cereal_sector_products1_idx` (`product_id` ASC, `products_supermarket_id` ASC) VISIBLE,
  CONSTRAINT `fk_cereal_sector_products`
    FOREIGN KEY (`product_id` , `products_supermarket_id`)
    REFERENCES `solvd_task`.`products` (`id` , `supermarket_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `solvd_task`.`equipments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solvd_task`.`equipments` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `supermarket_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_equipments_supermarkets1_idx` (`supermarket_id` ASC) VISIBLE,
  CONSTRAINT `fk_equipment_supermarket`
    FOREIGN KEY (`supermarket_id`)
    REFERENCES `solvd_task`.`supermarkets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;